version: '3.9'  # Utilisez une version plus récente si disponible
services:
  app:
    build: .
    ports:
      - "3002:3002"  # Mappe le port 3001 de l'hôte au port 3001 du conteneur
    volumes:
      - .:/app  # Monte le répertoire courant dans /app du conteneur
      - /app/node_modules  # Évite de remonter les node_modules du conteneur
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/F1_Timer  # URI de connexion à MongoDB
    command: npm run start  # Commande à exécuter pour démarrer l'application

  mongo:
    image: mongo:latest  # Utilise la dernière image officielle de MongoDB
    ports:
      - "27017:27017"  # Mappe le port 27017 de l'hôte au port 27017 du conteneur
    volumes:
      - mongo-data:/data/db  # Monte un volume nommé mongo-data pour la persistance des données

volumes:
  mongo-data:  # Déclare le volume mongo-data pour la persistance des données de MongoDB
