version: '3.9'

services:
  api-gateway:
    build: ./api_gateway
    ports:
      - "3001:3001"
    depends_on:
      - user-service
      - timer-service

  user-service:
    build: ./user_service
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongo-user:27017/user-service
    depends_on:
      - mongo-user

  timer-service:
    build: ./timer_service
    ports:
      - "3003:3003"
    environment:
      - MONGODB_URI=mongodb://mongo-timer:27017/timer-service
    depends_on:
      - mongo-timer

  mongo-user:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-user-data:/data/db

  mongo-timer:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-timer-data:/data/db

volumes:
  mongo-user-data:
  mongo-timer-data:
